In [90]:
import datetime
print(f"last updated:{datetime.datetime.now()}")

last updated:2024-09-18 00:19:57.596112


In [91]:
import numpy as np

In [92]:
print(np.__version__)

1.26.4


In [93]:
a1=np.array([1,2,3,4])

In [94]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [95]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [96]:
a1.shape,a1.ndim,a3.shape,a3.ndim

((4,), 1, (2, 3, 3), 3)

In [97]:
a2.ndim

2

In [98]:
type(a3)

numpy.ndarray

In [99]:
a3.dtype

dtype('int32')

In [100]:
import pandas as pd

In [101]:
df=pd.DataFrame(np.random.randint(10,size=(5,3)),columns=['a','b','c'])

In [102]:
df

a  b  c
0  9  1  4
1  6  8  2
2  3  0  0
3  6  0  6
4  3  3  8

In [103]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
np.ones(5).astype(int)

array([1, 1, 1, 1, 1])

In [105]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [106]:
random_array=np.random.randint(3,12,size=(5,4))
random_array

array([[11, 11,  5,  6],
       [ 5,  3, 11, 11],
       [ 6, 11,  5, 11],
       [ 7,  6,  3,  7],
       [ 6,  9, 11,  3]])

In [107]:
np.random.seed(0)
fixed_random=pd.DataFrame(np.random.randint(10,size=(5,4)),columns=('a','b','c','d'))
fixed_random

a  b  c  d
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6
3  8  8  1  6
4  7  7  8  1

In [108]:
equal_spaced=np.linspace(0,1,num=5)
equal_spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [109]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [110]:




a3,a3.T

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 array([[[ 1, 10],
         [ 4, 13],
         [ 7, 16]],
 
        [[ 2, 11],
         [ 5, 14],
         [ 8, 17]],
 
        [[ 3, 12],
         [ 6, 15],
         [ 9, 18]]]))

In [111]:
np.random.seed(0)
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]])

**manupulating and comparing array**

In [112]:
a1


array([1, 2, 3, 4])

In [113]:
a1=a1**2
a1



array([ 1,  4,  9, 16])

In [114]:
a2//2,a2/2

(array([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]], dtype=int32),
 array([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ],
        [3.5, 4. , 4.5]]))

In [115]:
a1=np.square(a1)

In [116]:
a1

array([  1,  16,  81, 256])

In [117]:
a1%2

array([1, 0, 1, 0], dtype=int32)

In [118]:
np.log(a1)

array([0.        , 2.77258872, 4.39444915, 5.54517744])

In [119]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [120]:
np.sum(a1),np.sum(a2),np.mean(a1),np.std(a1),np.max(a2),np.argmax(random_array)

(354, 45, 88.5, 101.27314550264546, 9, 0)

In [121]:
np.reshape(a3,(3,3,2),order='C'),np.reshape(a3,(3,3,2),order='F'),a3

(array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18]]]),
 array([[[ 1, 14],
         [13,  3],
         [ 2, 15]],
 
        [[10,  8],
         [ 7, 12],
         [11,  9]],
 
        [[ 4, 17],
         [16,  6],
         [ 5, 18]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [122]:
a2>=a3

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [123]:
a2!=3

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [124]:
a1.reshape(2,2)

array([[  1,  16],
       [ 81, 256]])

In [125]:
a1.T

array([  1,  16,  81, 256])

In [126]:
a2,a2.T

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [140]:
from matplotlib.image import imread

![a panda](panda[1].png)

In [141]:
panda=imread("panda[1].png")
print(type(panda))

<class 'numpy.ndarray'>


![a dog](dog-photo[1].png)

In [142]:
panda


array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0